#The name of the Spring Boot application (good practice for logging and tracing)
spring.application.name=forecastAPI

# Key for openweathermap.org API.
# This value is injected into the ForecastService using the @Value annotation.
openweathermap.api.key=8aa69c85b5dac61f9dc75c4219691a09